### ISSUE TITLE
`1f_.../first_deployment.tf` has inappropriate instance type, preventing build

### ISSUE THREAD

**Issue by 64kramsystem** [LevelUpEducation/terraform-tutorial#3]
The instance type provided with `1f_First_terraform_deployment/first_deployment.tf` is `t2.micro`, which requires a VPC.

Since the example is (as intended) very basic, it doesn't include any VPC, and any attempt to build will fail, with the error:

```
* aws_instance.example: Error launching source instance: VPCResourceNotSpecified: The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request.
```

The instance type should be changed to one that doesn't have such requirement, eg. `t1.micro`.

**Comment by stefanthorpe** [comment]
Please note: The configuration is designed to work on most EC2 accounts, with access to a default VPC. For EC2 Classic users, please use t1.micro for instance_type, and ami-408c7f28 for the ami. If you use a region other than us-east-1 then you will need to choose an AMI in that region as AMI IDs are region specific.
